// One command to get a working local genzen: Postgres and MinIO in
// docker-compose, the Supabase CLI stack, a populated `.env.local`, and a user
// to log in as. Idempotent -- run it as often as you like.
//
// Two databases run side by side for the length of #168: the Supabase stack
// still serves the app, and the plain Postgres is the one being migrated to.
// When Supabase goes, so do its blocks below and this script collapses to
// roughly ~/repos/bootsy/scripts/local-up.mjs, which is what it is modelled on.
//
//   pnpm local:up            start everything, then run the dev server
//   pnpm local:up --reset    additionally re-run `supabase db reset`
//   pnpm local:up --no-dev   set up only; don't start the dev server
//
// The only values you have to supply are your provider keys (FAL, then
// Anthropic), and this script asks you for each one it does not already have --
// so a re-run only prompts for what is still missing. Everything else --
// Supabase URL and keys, MinIO credentials -- is either
// generated by the tooling or a fixed local constant, so this script owns it
// outright and it never appears in front of a human. There is deliberately no
// `.env.local.example`: a template listing a dozen vars reads as "this needs
// configuring" when it does not.
import { spawn, spawnSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { createInterface } from 'node:readline/promises'
import { connect } from 'node:net'

const ROOT = new URL('../', import.meta.url)
const ENV_LOCAL = new URL('.env.local', ROOT)
const FORCE_RESET = process.argv.includes('--reset')
const SKIP_DEV = process.argv.includes('--no-dev')
/** Mirrors the `dev` script in package.json. */
const DEV_PORT = 3000
const DEV_URL = `http://localhost:${DEV_PORT}/`

/**
 * The local stack, in full. MinIO is on 9010/9011 rather than its defaults so
 * this can run alongside ~/repos/bootsy. The R2_ prefix is historical -- the
 * storage layer is plain S3 pointed by R2_ENDPOINT.
 *
 * Webhooks must stay false: localhost cannot receive them, and `true` disables
 * the polling loops that are the only other way results reach the UI.
 */
const LOCAL_ENV = {
  R2_ENDPOINT: 'http://localhost:9010',
  R2_ACCESS_KEY_ID: 'genzenlocal',
  R2_SECRET_ACCESS_KEY: 'genzenlocal',
  R2_BUCKET_NAME: 'genzen-images',
  R2_PUBLIC_URL: 'http://localhost:9010/genzen-images',
  VITE_R2_PUBLIC_URL: 'http://localhost:9010/genzen-images',
  ENABLE_FAL_WEBHOOKS: 'false',
  VITE_ENABLE_FAL_WEBHOOKS: 'false',
  // The #168 target database -- the `postgres` service in docker-compose.yml.
  // Port 5434 because 5432 is usually a system Postgres and 5433 is bootsy's.
  DATABASE_URL: 'postgres://genzen:genzen@localhost:5434/genzen',
}

/**
 * The local login. These live in `.env.local` so the credentials are yours to
 * change: edit them, re-run `local:up`, and the password is re-synced -- that is
 * the whole password-reset story, with no way for the file and the database to
 * disagree. Defaults match the user the Supabase seed has always created, so
 * nothing changes for an existing checkout.
 */
const DEV_USER_DEFAULTS = {
  LOCAL_DEV_EMAIL: 'testuser@gmail.com',
  LOCAL_DEV_PASSWORD: 'supa!1QAwsEDrf',
}

const ENV_HEADER = `# Generated by \`pnpm local:up\`. Only the provider keys are yours
# to set -- everything else is local plumbing this script manages for you.
`

function run(command, args, { capture = false } = {}) {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    stdio: capture ? 'pipe' : 'inherit',
    encoding: 'utf8',
  })
  if (result.status !== 0) {
    if (capture && result.stderr) process.stderr.write(result.stderr)
    console.error(`\nFailed: ${command} ${args.join(' ')}`)
    process.exit(result.status ?? 1)
  }
  return result.stdout ?? ''
}

/** Replace in place when present, append when not -- comments and order survive. */
function upsert(text, key, value) {
  const line = `${key}=${value}`
  const pattern = new RegExp(`^${key}=.*$`, 'm')
  return pattern.test(text)
    ? text.replace(pattern, line)
    : `${text.replace(/\s*$/, '')}\n${line}\n`
}

function read(key, text) {
  return (text.match(new RegExp(`^${key}=(.*)$`, 'm')) ?? [])[1]?.trim()
}

/** Is anything listening on this host:port? A plain TCP probe -- no HTTP. */
function hostPortInUse(host, port) {
  return new Promise((resolve) => {
    const socket = connect({ port, host })
    const settle = (result) => {
      socket.destroy()
      resolve(result)
    }
    socket.setTimeout(500)
    socket.once('connect', () => settle(true))
    socket.once('timeout', () => settle(false))
    socket.once('error', () => settle(false))
  })
}

/**
 * The dev server binds `localhost`, which resolves to ::1 before 127.0.0.1 on
 * macOS -- so probing only IPv4 can miss a server that is very much running,
 * and we'd start a second one. Check both.
 */
async function portInUse(port) {
  const results = await Promise.all([
    hostPortInUse('127.0.0.1', port),
    hostPortInUse('::1', port),
  ])
  return results.some(Boolean)
}

function openBrowser(url) {
  const opener =
    process.platform === 'darwin'
      ? ['open', [url]]
      : process.platform === 'win32'
        ? ['cmd', ['/c', 'start', '', url]]
        : ['xdg-open', [url]]
  spawnSync(opener[0], opener[1], { stdio: 'ignore' })
}

// 1. Docker preflight, so a stopped daemon reads as a sentence rather than an
//    opaque compose error.
if (spawnSync('docker', ['info'], { stdio: 'ignore' }).status !== 0) {
  console.error(
    'Docker is not running. Start Docker Desktop (or your daemon) and re-run.',
  )
  process.exit(1)
}

// 1b. Supabase CLI preflight. It is a global tool, not a dependency of this
//     repo, so a fresh machine has Docker and pnpm but not this -- and without
//     the check the failure is the unhelpful `Failed: supabase start`.
if (spawnSync('supabase', ['--version'], { stdio: 'ignore' }).status !== 0) {
  console.error(`The Supabase CLI is not installed (it is a global tool, not an npm dependency).

  macOS:  brew install supabase/tap/supabase
  other:  https://supabase.com/docs/guides/local-development/cli/getting-started

Then re-run \`pnpm local:up\`.`)
  process.exit(1)
}

// 2. Containers. `--wait` is the wait-for-healthy mechanism -- no sleep loops.
console.log('\n> starting postgres + minio')
run('docker', ['compose', 'up', '-d', '--wait', 'postgres', 'minio'])
console.log('\n> ensuring bucket')
run('docker', ['compose', 'run', '--rm', 'createbucket'])

// 3. Supabase. Idempotent: a no-op when the containers are already up.
console.log('\n> starting supabase')
run('supabase', ['start'])

// 4. Read the generated credentials back out.
const status = JSON.parse(
  run('supabase', ['status', '-o', 'json'], { capture: true }),
)
const apiUrl = status.API_URL
const anonKey = status.ANON_KEY
const serviceRoleKey = status.SERVICE_ROLE_KEY
if (!apiUrl || !anonKey || !serviceRoleKey) {
  console.error(
    'Could not read API_URL / ANON_KEY / SERVICE_ROLE_KEY from `supabase status`.',
  )
  process.exit(1)
}

// 5. Own `.env.local` outright. Upserting (rather than copying a template)
//    is what keeps FAL_KEY intact on a re-run.
if (!existsSync(ENV_LOCAL)) {
  writeFileSync(ENV_LOCAL, `${ENV_HEADER}\nFAL_KEY=\nANTHROPIC_API_KEY=\n`)
  console.log('\ncreated .env.local')
}
let env = readFileSync(ENV_LOCAL, 'utf8')

// Generated once and then left alone: rotating it would sign every existing
// session cookie out, and there is no reason for a human to ever see it.
if (!read('AUTH_SESSION_SECRET', env)) {
  env = upsert(env, 'AUTH_SESSION_SECRET', randomBytes(32).toString('hex'))
  console.log('.env.local: generated AUTH_SESSION_SECRET')
}

// Seeded only when absent, so an edited login survives a re-run.
for (const [key, value] of Object.entries(DEV_USER_DEFAULTS)) {
  if (!read(key, env)) env = upsert(env, key, value)
}

for (const [key, value] of [
  ...Object.entries(LOCAL_ENV),
  ['VITE_SUPABASE_URL', apiUrl],
  ['VITE_SUPABASE_ANON_KEY', anonKey],
  ['SUPABASE_SERVICE_ROLE_KEY', serviceRoleKey],
]) {
  env = upsert(env, key, value)
}
writeFileSync(ENV_LOCAL, env)
console.log('.env.local: local config synced')

// 6. Schema. Probe PostgREST for `user_images` rather than resetting blindly --
//    a routine `local:up` must never nuke a database you have been working in.
//    `--reset` is the deliberate path.
let hasSchema = false
try {
  const probe = await fetch(`${apiUrl}/rest/v1/user_images?select=id&limit=0`, {
    headers: { apikey: anonKey, Authorization: `Bearer ${anonKey}` },
  })
  hasSchema = probe.status !== 404
} catch {
  hasSchema = false
}

if (FORCE_RESET || !hasSchema) {
  console.log(
    `\n> ${FORCE_RESET ? 'resetting database (--reset)' : 'applying migrations + seed (fresh database)'}`,
  )
  run('supabase', ['db', 'reset'])
} else {
  console.log(
    '\nschema already present -- skipping db reset (use --reset to force)',
  )
}

// 6b. The #168 Postgres: migrate, then provision the dev login.
//
//     Unlike the Supabase block above there is no reset branch and none is
//     needed -- `scripts/migrate.mjs` only applies files not already recorded in
//     `schema_migrations`, so re-running it against a database you have been
//     working in is a no-op rather than a risk.
console.log('\n> migrating postgres')
run('node', ['scripts/migrate.mjs'])

// Provisioning is the whitelist once Supabase auth is gone -- a fresh database
// has no way in without this. The password is re-synced on every run rather than
// skipped when the row exists, so `.env.local` stays the source of truth.
// Guarded by DATABASE_URL pointing at the local stack, which is a fixed constant
// in this script; `pnpm auth:create-user` is still the path for a real account,
// and it prompts before touching anything remote.
{
  const { default: postgres } = await import('postgres')
  const { hashPassword } = await import('./hash-lib.mjs')
  const devEmail =
    read('LOCAL_DEV_EMAIL', env) ?? DEV_USER_DEFAULTS.LOCAL_DEV_EMAIL
  const devPassword =
    read('LOCAL_DEV_PASSWORD', env) ?? DEV_USER_DEFAULTS.LOCAL_DEV_PASSWORD

  // For as long as both databases exist, the local user must carry the SAME id
  // as its Supabase auth row. `user_images.user_id` still references
  // `auth.users(id)`, and the app now derives identity from the local `users`
  // table -- so a mismatch means your library reads empty and every upload dies
  // on a foreign key after the file has already reached storage. Adopting the
  // auth uuid keeps one identity across the transition. This whole block goes
  // when Supabase does (#176).
  const supabaseSql = postgres(
    'postgres://postgres:postgres@localhost:54322/postgres',
  )
  let authUserId
  try {
    const [authUser] = await supabaseSql`
      select id from auth.users where email = ${devEmail}
    `
    authUserId = authUser?.id
  } catch {
    // No auth schema (or Supabase already gone) -- fall back to a generated id.
  } finally {
    await supabaseSql.end()
  }

  const sql = postgres(LOCAL_ENV.DATABASE_URL)
  try {
    const passwordHash = await hashPassword(devPassword)
    const [existing] = await sql`select id from users where email = ${devEmail}`
    if (existing) {
      await sql`update users set password_hash = ${passwordHash} where id = ${existing.id}`
      if (authUserId && existing.id !== authUserId) {
        await sql`update users set id = ${authUserId} where id = ${existing.id}`
        console.log(
          `postgres: ${devEmail} -- adopted the Supabase auth id (${authUserId}) so existing images stay yours`,
        )
      }
      console.log(`postgres: ${devEmail} -- password synced from .env.local`)
    } else if (authUserId) {
      await sql`
        insert into users (id, email, password_hash)
        values (${authUserId}, ${devEmail}, ${passwordHash})
      `
      console.log(`postgres: created ${devEmail} / ${devPassword}`)
    } else {
      await sql`insert into users (email, password_hash) values (${devEmail}, ${passwordHash})`
      console.log(`postgres: created ${devEmail} / ${devPassword}`)
    }
  } finally {
    await sql.end()
  }
}

// 7. The things that are actually yours: the provider keys. Ask for each one
//    that is missing rather than printing a warning and leaving you to find the
//    right file and var name. A re-run only prompts for what is still absent,
//    so adding a key later costs one command and one paste.
const PROVIDER_KEYS = [
  {
    envVar: 'FAL_KEY',
    label: 'FAL',
    where: 'https://fal.ai/dashboard/keys',
    needed: 'image generation',
    consequence: 'the app runs, but image generation will fail',
  },
  {
    envVar: 'ANTHROPIC_API_KEY',
    label: 'Anthropic',
    where: 'https://console.anthropic.com/settings/keys',
    needed: 'the AI features layered on top of plain image generation',
    note: `Strongly recommended. Without it the app still runs and images still
generate, but Enhance Prompt, variation prompts, shot lists and Describe will
each tell you the key is missing instead of working.`,
    consequence:
      'image generation still works, but the AI-assisted features will report the missing key',
  },
]

for (const key of PROVIDER_KEYS) {
  const shellValue = process.env[key.envVar]
  let fileValue = read(key.envVar, readFileSync(ENV_LOCAL, 'utf8'))

  if (shellValue && shellValue !== fileValue) {
    // An exported value wins over .env.local -- dotenv does not overwrite
    // something already in process.env. A genuinely nasty trap: you paste a
    // fresh key into .env.local, nothing changes, and it fails exactly as
    // before. Prompting here would be a lie, since whatever we wrote would
    // still be shadowed.
    console.warn(
      `\n!! ${key.envVar} is exported in your shell (${shellValue.slice(0, 6)}...) and OVERRIDES .env.local.`,
    )
    console.warn(
      '   Editing .env.local will have no effect while that export exists.',
    )
    console.warn(
      '   Fix the exported value (check ~/.secrets.zsh), or unset it to let .env.local win.',
    )
    continue
  }

  if (fileValue) continue

  if (process.stdin.isTTY) {
    console.log(`
${key.label} key -- powers ${key.needed}.${key.note ? `\n${key.note}` : ''}
Get one at ${key.where} (leave blank to skip -- you can re-run
\`pnpm local:up\` later and it will ask again for whatever is still missing).`)
    const rl = createInterface({ input: process.stdin, output: process.stdout })
    const answer = (await rl.question(`\nPaste your ${key.label} key: `)).trim()
    rl.close()
    if (answer) {
      writeFileSync(
        ENV_LOCAL,
        upsert(readFileSync(ENV_LOCAL, 'utf8'), key.envVar, answer),
      )
      fileValue = answer
      console.log(`${key.envVar} saved to .env.local`)
    }
  }

  if (!fileValue) {
    console.warn(`\nNo ${key.envVar} set -- ${key.consequence}.`)
    console.warn('Add one any time by re-running `pnpm local:up`.')
  }
}

console.log(`
Ready.
  app                      ${DEV_URL}
  sign in as               ${read('LOCAL_DEV_EMAIL', env) ?? DEV_USER_DEFAULTS.LOCAL_DEV_EMAIL} / ${read('LOCAL_DEV_PASSWORD', env) ?? DEV_USER_DEFAULTS.LOCAL_DEV_PASSWORD}
  MinIO console            http://localhost:9011 (genzenlocal / genzenlocal)
  Supabase Studio          http://localhost:54323
  Postgres (#168 target)   postgres://genzen:genzen@localhost:5434/genzen
`)

// 8. Hand back a running app rather than an instruction to start one. If a dev
//    server is already up on the port, don't start a second one -- just open it.
if (SKIP_DEV) {
  console.log('--no-dev: skipping the dev server. Start it with `pnpm dev`.')
} else if (await portInUse(DEV_PORT)) {
  // A TCP probe can't tell genzen's dev server from anything else on :3000, so
  // say which port is being reused rather than claiming it's ours.
  console.log(`Something is already serving :${DEV_PORT} -- opening it.`)
  openBrowser(DEV_URL)
} else {
  console.log('> starting dev server (ctrl-c to stop)\n')
  // Vite had a `--open` flag that launched the browser once it was listening.
  // Next does not, and passing it is a hard error, so poll the port instead --
  // which is what the flag was saving us from doing.
  const dev = spawn('pnpm', ['dev'], { cwd: ROOT, stdio: 'inherit' })

  void (async () => {
    for (let attempt = 0; attempt < 60; attempt++) {
      if (dev.exitCode !== null) return
      if (await portInUse(DEV_PORT)) {
        openBrowser(DEV_URL)
        return
      }
      await new Promise((resolve) => setTimeout(resolve, 500))
    }
    // 30s and still nothing listening: the server is having trouble and its own
    // output is the useful signal, so say nothing rather than open a dead tab.
  })()

  dev.on('exit', (code, signal) => {
    // Ctrl-C arrives as a signal, not a failure -- exiting 1 on it would be a lie.
    process.exit(signal ? 0 : (code ?? 0))
  })
}
