// One command to get a working local genzen: MinIO in docker-compose, the
// Supabase CLI stack, a populated `.env.local`, and a seeded user to log in
// as. Idempotent -- run it as often as you like.
//
//   pnpm local:up            start everything, leave existing data alone
//   pnpm local:up --reset    additionally re-run `supabase db reset`
//
// The only values you have to supply are your provider keys (FAL, then
// Anthropic), and this script asks you for each one it does not already have --
// so a re-run only prompts for what is still missing. Everything else --
// Supabase URL and keys, MinIO credentials -- is either
// generated by the tooling or a fixed local constant, so this script owns it
// outright and it never appears in front of a human. There is deliberately no
// `.env.local.example`: a template listing a dozen vars reads as "this needs
// configuring" when it does not.
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { createInterface } from 'node:readline/promises'

const ROOT = new URL('../', import.meta.url)
const ENV_LOCAL = new URL('.env.local', ROOT)
const FORCE_RESET = process.argv.includes('--reset')

/**
 * The local stack, in full. MinIO is on 9010/9011 rather than its defaults so
 * this can run alongside ~/repos/bootsy. The R2_ prefix is historical -- the
 * storage layer is plain S3 pointed by R2_ENDPOINT.
 *
 * Webhooks must stay false: localhost cannot receive them, and `true` disables
 * the polling loops that are the only other way results reach the UI.
 */
const LOCAL_ENV = {
  R2_ENDPOINT: 'http://localhost:9010',
  R2_ACCESS_KEY_ID: 'genzenlocal',
  R2_SECRET_ACCESS_KEY: 'genzenlocal',
  R2_BUCKET_NAME: 'genzen-images',
  R2_PUBLIC_URL: 'http://localhost:9010/genzen-images',
  VITE_R2_PUBLIC_URL: 'http://localhost:9010/genzen-images',
  ENABLE_FAL_WEBHOOKS: 'false',
  VITE_ENABLE_FAL_WEBHOOKS: 'false',
}

const ENV_HEADER = `# Generated by \`pnpm local:up\`. Only the provider keys are yours
# to set -- everything else is local plumbing this script manages for you.
`

function run(command, args, { capture = false } = {}) {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    stdio: capture ? 'pipe' : 'inherit',
    encoding: 'utf8',
  })
  if (result.status !== 0) {
    if (capture && result.stderr) process.stderr.write(result.stderr)
    console.error(`\nFailed: ${command} ${args.join(' ')}`)
    process.exit(result.status ?? 1)
  }
  return result.stdout ?? ''
}

/** Replace in place when present, append when not -- comments and order survive. */
function upsert(text, key, value) {
  const line = `${key}=${value}`
  const pattern = new RegExp(`^${key}=.*$`, 'm')
  return pattern.test(text)
    ? text.replace(pattern, line)
    : `${text.replace(/\s*$/, '')}\n${line}\n`
}

function read(key, text) {
  return (text.match(new RegExp(`^${key}=(.*)$`, 'm')) ?? [])[1]?.trim()
}

// 1. Docker preflight, so a stopped daemon reads as a sentence rather than an
//    opaque compose error.
if (spawnSync('docker', ['info'], { stdio: 'ignore' }).status !== 0) {
  console.error(
    'Docker is not running. Start Docker Desktop (or your daemon) and re-run.',
  )
  process.exit(1)
}

// 1b. Supabase CLI preflight. It is a global tool, not a dependency of this
//     repo, so a fresh machine has Docker and pnpm but not this -- and without
//     the check the failure is the unhelpful `Failed: supabase start`.
if (spawnSync('supabase', ['--version'], { stdio: 'ignore' }).status !== 0) {
  console.error(`The Supabase CLI is not installed (it is a global tool, not an npm dependency).

  macOS:  brew install supabase/tap/supabase
  other:  https://supabase.com/docs/guides/local-development/cli/getting-started

Then re-run \`pnpm local:up\`.`)
  process.exit(1)
}

// 2. MinIO. `--wait` is the wait-for-healthy mechanism -- no sleep loops.
console.log('\n> starting minio')
run('docker', ['compose', 'up', '-d', '--wait', 'minio'])
console.log('\n> ensuring bucket')
run('docker', ['compose', 'run', '--rm', 'createbucket'])

// 3. Supabase. Idempotent: a no-op when the containers are already up.
console.log('\n> starting supabase')
run('supabase', ['start'])

// 4. Read the generated credentials back out.
const status = JSON.parse(
  run('supabase', ['status', '-o', 'json'], { capture: true }),
)
const apiUrl = status.API_URL
const anonKey = status.ANON_KEY
const serviceRoleKey = status.SERVICE_ROLE_KEY
if (!apiUrl || !anonKey || !serviceRoleKey) {
  console.error(
    'Could not read API_URL / ANON_KEY / SERVICE_ROLE_KEY from `supabase status`.',
  )
  process.exit(1)
}

// 5. Own `.env.local` outright. Upserting (rather than copying a template)
//    is what keeps FAL_KEY intact on a re-run.
if (!existsSync(ENV_LOCAL)) {
  writeFileSync(ENV_LOCAL, `${ENV_HEADER}\nFAL_KEY=\nANTHROPIC_API_KEY=\n`)
  console.log('\ncreated .env.local')
}
let env = readFileSync(ENV_LOCAL, 'utf8')
for (const [key, value] of [
  ...Object.entries(LOCAL_ENV),
  ['VITE_SUPABASE_URL', apiUrl],
  ['VITE_SUPABASE_ANON_KEY', anonKey],
  ['SUPABASE_SERVICE_ROLE_KEY', serviceRoleKey],
]) {
  env = upsert(env, key, value)
}
writeFileSync(ENV_LOCAL, env)
console.log('.env.local: local config synced')

// 6. Schema. Probe PostgREST for `user_images` rather than resetting blindly --
//    a routine `local:up` must never nuke a database you have been working in.
//    `--reset` is the deliberate path.
let hasSchema = false
try {
  const probe = await fetch(`${apiUrl}/rest/v1/user_images?select=id&limit=0`, {
    headers: { apikey: anonKey, Authorization: `Bearer ${anonKey}` },
  })
  hasSchema = probe.status !== 404
} catch {
  hasSchema = false
}

if (FORCE_RESET || !hasSchema) {
  console.log(
    `\n> ${FORCE_RESET ? 'resetting database (--reset)' : 'applying migrations + seed (fresh database)'}`,
  )
  run('supabase', ['db', 'reset'])
} else {
  console.log(
    '\nschema already present -- skipping db reset (use --reset to force)',
  )
}

// 7. The things that are actually yours: the provider keys. Ask for each one
//    that is missing rather than printing a warning and leaving you to find the
//    right file and var name. A re-run only prompts for what is still absent,
//    so adding a key later costs one command and one paste.
const PROVIDER_KEYS = [
  {
    envVar: 'FAL_KEY',
    label: 'FAL',
    where: 'https://fal.ai/dashboard/keys',
    needed: 'image generation',
    consequence: 'the app runs, but image generation will fail',
  },
  {
    envVar: 'ANTHROPIC_API_KEY',
    label: 'Anthropic',
    where: 'https://console.anthropic.com/settings/keys',
    needed: 'the AI features layered on top of plain image generation',
    note: `Strongly recommended. Without it the app still runs and images still
generate, but Enhance Prompt, variation prompts, shot lists and Describe will
each tell you the key is missing instead of working.`,
    consequence:
      'image generation still works, but the AI-assisted features will report the missing key',
  },
]

for (const key of PROVIDER_KEYS) {
  const shellValue = process.env[key.envVar]
  let fileValue = read(key.envVar, readFileSync(ENV_LOCAL, 'utf8'))

  if (shellValue && shellValue !== fileValue) {
    // An exported value wins over .env.local -- dotenv does not overwrite
    // something already in process.env. A genuinely nasty trap: you paste a
    // fresh key into .env.local, nothing changes, and it fails exactly as
    // before. Prompting here would be a lie, since whatever we wrote would
    // still be shadowed.
    console.warn(
      `\n!! ${key.envVar} is exported in your shell (${shellValue.slice(0, 6)}...) and OVERRIDES .env.local.`,
    )
    console.warn(
      '   Editing .env.local will have no effect while that export exists.',
    )
    console.warn(
      '   Fix the exported value (check ~/.secrets.zsh), or unset it to let .env.local win.',
    )
    continue
  }

  if (fileValue) continue

  if (process.stdin.isTTY) {
    console.log(`
${key.label} key -- powers ${key.needed}.${key.note ? `\n${key.note}` : ''}
Get one at ${key.where} (leave blank to skip -- you can re-run
\`pnpm local:up\` later and it will ask again for whatever is still missing).`)
    const rl = createInterface({ input: process.stdin, output: process.stdout })
    const answer = (await rl.question(`\nPaste your ${key.label} key: `)).trim()
    rl.close()
    if (answer) {
      writeFileSync(
        ENV_LOCAL,
        upsert(readFileSync(ENV_LOCAL, 'utf8'), key.envVar, answer),
      )
      fileValue = answer
      console.log(`${key.envVar} saved to .env.local`)
    }
  }

  if (!fileValue) {
    console.warn(`\nNo ${key.envVar} set -- ${key.consequence}.`)
    console.warn('Add one any time by re-running `pnpm local:up`.')
  }
}

console.log(`
Ready.
  pnpm dev                 http://localhost:3000
  sign in as               testuser@gmail.com / supa!1QAwsEDrf
  MinIO console            http://localhost:9011 (genzenlocal / genzenlocal)
  Supabase Studio          http://localhost:54323
`)
