// One command to get a working local genzen: Postgres and MinIO in
// docker-compose, a populated `.env.local`, and a user to log in as.
// Idempotent -- run it as often as you like.
//
// Prerequisites are Docker and pnpm, and nothing else. There is no global CLI
// to install: that was the Supabase one, and it went with #176.
//
//   pnpm local:up            start everything, then run the dev server
//   pnpm local:up --no-dev   set up only; don't start the dev server
//
// The only values you have to supply are your provider keys (FAL, then
// Anthropic), and this script asks you for each one it does not already have --
// so a re-run only prompts for what is still missing. Everything else --
// MinIO credentials, the database URL -- is
// a fixed local constant, so this script owns it outright and it never appears
// in front of a human. There is deliberately no
// `.env.local.example`: a template listing a dozen vars reads as "this needs
// configuring" when it does not.
import { spawn, spawnSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { createInterface } from 'node:readline/promises'
import { connect } from 'node:net'

const ROOT = new URL('../', import.meta.url)
const ENV_LOCAL = new URL('.env.local', ROOT)
const SKIP_DEV = process.argv.includes('--no-dev')
/** Mirrors the `dev` script in package.json. */
const DEV_PORT = 3000
const DEV_URL = `http://localhost:${DEV_PORT}/`

/**
 * The local stack, in full. MinIO is on 9010/9011 rather than its defaults so
 * this can run alongside ~/repos/bootsy. The R2_ prefix is historical -- the
 * storage layer is plain S3 pointed by R2_ENDPOINT.
 *
 */
const LOCAL_ENV = {
  R2_ENDPOINT: 'http://localhost:9010',
  R2_ACCESS_KEY_ID: 'genzenlocal',
  R2_SECRET_ACCESS_KEY: 'genzenlocal',
  R2_BUCKET_NAME: 'genzen-images',
  // The `postgres` service in docker-compose.yml. Port 5434 because 5432 is
  // usually a system Postgres and 5433 is bootsy's.
  DATABASE_URL: 'postgres://genzen:genzen@localhost:5434/genzen',
}

/**
 * The local login. These live in `.env.local` so the credentials are yours to
 * change: edit them, re-run `local:up`, and the password is re-synced -- that is
 * the whole password-reset story, with no way for the file and the database to
 * disagree.
 *
 * The password is **generated**, not a constant, and the address is a reserved
 * domain. A checked-in default would be a real credential published in a public
 * repo, and the one that was here was a password its author used elsewhere.
 * Generating per-clone also means two machines never share a local login.
 */
const DEV_USER_DEFAULTS = {
  LOCAL_DEV_EMAIL: 'dev@example.com',
  LOCAL_DEV_PASSWORD: randomBytes(9).toString('base64url'),
}

const ENV_HEADER = `# Generated by \`pnpm local:up\`. Only the provider keys are yours
# to set -- everything else is local plumbing this script manages for you.
`

function run(command, args, { capture = false } = {}) {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    stdio: capture ? 'pipe' : 'inherit',
    encoding: 'utf8',
  })
  if (result.status !== 0) {
    if (capture && result.stderr) process.stderr.write(result.stderr)
    console.error(`\nFailed: ${command} ${args.join(' ')}`)
    process.exit(result.status ?? 1)
  }
  return result.stdout ?? ''
}

/** Replace in place when present, append when not -- comments and order survive. */
function upsert(text, key, value) {
  const line = `${key}=${value}`
  const pattern = new RegExp(`^${key}=.*$`, 'm')
  return pattern.test(text)
    ? text.replace(pattern, line)
    : `${text.replace(/\s*$/, '')}\n${line}\n`
}

function read(key, text) {
  return (text.match(new RegExp(`^${key}=(.*)$`, 'm')) ?? [])[1]?.trim()
}

/** Is anything listening on this host:port? A plain TCP probe -- no HTTP. */
function hostPortInUse(host, port) {
  return new Promise((resolve) => {
    const socket = connect({ port, host })
    const settle = (result) => {
      socket.destroy()
      resolve(result)
    }
    socket.setTimeout(500)
    socket.once('connect', () => settle(true))
    socket.once('timeout', () => settle(false))
    socket.once('error', () => settle(false))
  })
}

/**
 * The dev server binds `localhost`, which resolves to ::1 before 127.0.0.1 on
 * macOS -- so probing only IPv4 can miss a server that is very much running,
 * and we'd start a second one. Check both.
 */
async function portInUse(port) {
  const results = await Promise.all([
    hostPortInUse('127.0.0.1', port),
    hostPortInUse('::1', port),
  ])
  return results.some(Boolean)
}

function openBrowser(url) {
  const opener =
    process.platform === 'darwin'
      ? ['open', [url]]
      : process.platform === 'win32'
        ? ['cmd', ['/c', 'start', '', url]]
        : ['xdg-open', [url]]
  spawnSync(opener[0], opener[1], { stdio: 'ignore' })
}

// 1. Docker preflight, so a stopped daemon reads as a sentence rather than an
//    opaque compose error.
if (spawnSync('docker', ['info'], { stdio: 'ignore' }).status !== 0) {
  console.error(
    'Docker is not running. Start Docker Desktop (or your daemon) and re-run.',
  )
  process.exit(1)
}

// 2. Containers. `--wait` is the wait-for-healthy mechanism -- no sleep loops.
console.log('\n> starting postgres + minio')
run('docker', ['compose', 'up', '-d', '--wait', 'postgres', 'minio'])
console.log('\n> ensuring bucket')
run('docker', ['compose', 'run', '--rm', 'createbucket'])

// 3. Own `.env.local` outright. Upserting (rather than copying a template)
//    is what keeps FAL_KEY intact on a re-run.
if (!existsSync(ENV_LOCAL)) {
  writeFileSync(ENV_LOCAL, `${ENV_HEADER}\nFAL_KEY=\nANTHROPIC_API_KEY=\n`)
  console.log('\ncreated .env.local')
}
let env = readFileSync(ENV_LOCAL, 'utf8')

// Generated once and then left alone: rotating it would sign every existing
// session cookie out, and there is no reason for a human to ever see it.
if (!read('AUTH_SESSION_SECRET', env)) {
  env = upsert(env, 'AUTH_SESSION_SECRET', randomBytes(32).toString('hex'))
  console.log('.env.local: generated AUTH_SESSION_SECRET')
}

// Seeded only when absent, so an edited login survives a re-run.
for (const [key, value] of Object.entries(DEV_USER_DEFAULTS)) {
  if (!read(key, env)) env = upsert(env, key, value)
}

for (const [key, value] of Object.entries(LOCAL_ENV)) {
  env = upsert(env, key, value)
}
writeFileSync(ENV_LOCAL, env)
console.log('.env.local: local config synced')

// 4. Schema. `scripts/migrate.mjs` only applies files not already recorded in
//    `schema_migrations`, so re-running it against a database you have been
//    working in is a no-op rather than a risk -- which is why there is no
//    reset branch here and none is needed.
console.log('\n> migrating postgres')
run('node', ['scripts/migrate.mjs'])

// 5. The dev login. Provisioning is the whole whitelist -- a fresh database has
//    no way in without it. The password is re-synced on every run rather than
//    skipped when the row exists, so `.env.local` stays the source of truth.
//    Guarded by DATABASE_URL pointing at the local stack, which is a fixed
//    constant in this script; `pnpm users add` is the path for any other
//    account, and it prompts before touching anything remote.
{
  const { default: postgres } = await import('postgres')
  const { hashPassword } = await import('./hash-lib.mjs')
  const devEmail =
    read('LOCAL_DEV_EMAIL', env) ?? DEV_USER_DEFAULTS.LOCAL_DEV_EMAIL
  const devPassword =
    read('LOCAL_DEV_PASSWORD', env) ?? DEV_USER_DEFAULTS.LOCAL_DEV_PASSWORD

  const sql = postgres(LOCAL_ENV.DATABASE_URL)
  try {
    const passwordHash = await hashPassword(devPassword)
    const [existing] = await sql`select id from users where email = ${devEmail}`
    if (existing) {
      await sql`update users set password_hash = ${passwordHash} where id = ${existing.id}`
      console.log(`postgres: ${devEmail} -- password synced from .env.local`)
    } else {
      await sql`insert into users (email, password_hash) values (${devEmail}, ${passwordHash})`
      console.log(`postgres: created ${devEmail} / ${devPassword}`)
    }
  } finally {
    await sql.end()
  }
}

// 7. The things that are actually yours: the provider keys. Ask for each one
//    that is missing rather than printing a warning and leaving you to find the
//    right file and var name. A re-run only prompts for what is still absent,
//    so adding a key later costs one command and one paste.
const PROVIDER_KEYS = [
  {
    envVar: 'FAL_KEY',
    label: 'FAL',
    where: 'https://fal.ai/dashboard/keys',
    needed: 'image generation',
    consequence: 'the app runs, but image generation will fail',
  },
  {
    envVar: 'ANTHROPIC_API_KEY',
    label: 'Anthropic',
    where: 'https://console.anthropic.com/settings/keys',
    needed: 'the AI features layered on top of plain image generation',
    note: `Strongly recommended. Without it the app still runs and images still
generate, but Enhance Prompt, variation prompts, shot lists and Describe will
each tell you the key is missing instead of working.`,
    consequence:
      'image generation still works, but the AI-assisted features will report the missing key',
  },
]

for (const key of PROVIDER_KEYS) {
  const shellValue = process.env[key.envVar]
  let fileValue = read(key.envVar, readFileSync(ENV_LOCAL, 'utf8'))

  if (shellValue && shellValue !== fileValue) {
    // An exported value wins over .env.local -- dotenv does not overwrite
    // something already in process.env. A genuinely nasty trap: you paste a
    // fresh key into .env.local, nothing changes, and it fails exactly as
    // before. Prompting here would be a lie, since whatever we wrote would
    // still be shadowed.
    console.warn(
      `\n!! ${key.envVar} is exported in your shell (${shellValue.slice(0, 6)}...) and OVERRIDES .env.local.`,
    )
    console.warn(
      '   Editing .env.local will have no effect while that export exists.',
    )
    console.warn(
      '   Fix the exported value (check ~/.secrets.zsh), or unset it to let .env.local win.',
    )
    continue
  }

  if (fileValue) continue

  if (process.stdin.isTTY) {
    console.log(`
${key.label} key -- powers ${key.needed}.${key.note ? `\n${key.note}` : ''}
Get one at ${key.where} (leave blank to skip -- you can re-run
\`pnpm local:up\` later and it will ask again for whatever is still missing).`)
    const rl = createInterface({ input: process.stdin, output: process.stdout })
    const answer = (await rl.question(`\nPaste your ${key.label} key: `)).trim()
    rl.close()
    if (answer) {
      writeFileSync(
        ENV_LOCAL,
        upsert(readFileSync(ENV_LOCAL, 'utf8'), key.envVar, answer),
      )
      fileValue = answer
      console.log(`${key.envVar} saved to .env.local`)
    }
  }

  if (!fileValue) {
    console.warn(`\nNo ${key.envVar} set -- ${key.consequence}.`)
    console.warn('Add one any time by re-running `pnpm local:up`.')
  }
}

console.log(`
Ready.
  app                      ${DEV_URL}
  sign in as               ${read('LOCAL_DEV_EMAIL', env) ?? DEV_USER_DEFAULTS.LOCAL_DEV_EMAIL} / ${read('LOCAL_DEV_PASSWORD', env) ?? DEV_USER_DEFAULTS.LOCAL_DEV_PASSWORD}
  MinIO console            http://localhost:9011 (genzenlocal / genzenlocal)
  Postgres                 postgres://genzen:genzen@localhost:5434/genzen
`)

// 8. Hand back a running app rather than an instruction to start one. If a dev
//    server is already up on the port, don't start a second one -- just open it.
if (SKIP_DEV) {
  console.log('--no-dev: skipping the dev server. Start it with `pnpm dev`.')
} else if (await portInUse(DEV_PORT)) {
  // A TCP probe can't tell genzen's dev server from anything else on :3000, so
  // say which port is being reused rather than claiming it's ours.
  console.log(`Something is already serving :${DEV_PORT} -- opening it.`)
  openBrowser(DEV_URL)
} else {
  console.log('> starting dev server (ctrl-c to stop)\n')
  // Vite had a `--open` flag that launched the browser once it was listening.
  // Next does not, and passing it is a hard error, so poll the port instead --
  // which is what the flag was saving us from doing.
  const dev = spawn('pnpm', ['dev'], { cwd: ROOT, stdio: 'inherit' })

  void (async () => {
    for (let attempt = 0; attempt < 60; attempt++) {
      if (dev.exitCode !== null) return
      if (await portInUse(DEV_PORT)) {
        openBrowser(DEV_URL)
        return
      }
      await new Promise((resolve) => setTimeout(resolve, 500))
    }
    // 30s and still nothing listening: the server is having trouble and its own
    // output is the useful signal, so say nothing rather than open a dead tab.
  })()

  dev.on('exit', (code, signal) => {
    // Ctrl-C arrives as a signal, not a failure -- exiting 1 on it would be a lie.
    process.exit(signal ? 0 : (code ?? 0))
  })
}
