/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DashboardVideoRouteImport } from './routes/dashboard/video'
import { Route as DashboardStatusRouteImport } from './routes/dashboard/status'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardImagesRouteImport } from './routes/dashboard/images'
import { Route as DashboardAiImagesRouteImport } from './routes/dashboard/ai-images'
import { Route as DashboardVideoIndexRouteImport } from './routes/dashboard/video.index'
import { Route as DashboardVideoWorkspaceIdRouteImport } from './routes/dashboard/video.$workspaceId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardVideoRoute = DashboardVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatusRoute = DashboardStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImagesRoute = DashboardImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiImagesRoute = DashboardAiImagesRouteImport.update({
  id: '/ai-images',
  path: '/ai-images',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVideoIndexRoute = DashboardVideoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardVideoRoute,
} as any)
const DashboardVideoWorkspaceIdRoute =
  DashboardVideoWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => DashboardVideoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai-images': typeof DashboardAiImagesRoute
  '/dashboard/images': typeof DashboardImagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/video': typeof DashboardVideoRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/video/$workspaceId': typeof DashboardVideoWorkspaceIdRoute
  '/dashboard/video/': typeof DashboardVideoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai-images': typeof DashboardAiImagesRoute
  '/dashboard/images': typeof DashboardImagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/docs/$': typeof DocsSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard/video/$workspaceId': typeof DashboardVideoWorkspaceIdRoute
  '/dashboard/video': typeof DashboardVideoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai-images': typeof DashboardAiImagesRoute
  '/dashboard/images': typeof DashboardImagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/status': typeof DashboardStatusRoute
  '/dashboard/video': typeof DashboardVideoRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard/video/$workspaceId': typeof DashboardVideoWorkspaceIdRoute
  '/dashboard/video/': typeof DashboardVideoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/ai-images'
    | '/dashboard/images'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/status'
    | '/dashboard/video'
    | '/docs/$'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/video/$workspaceId'
    | '/dashboard/video/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/ai-images'
    | '/dashboard/images'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/status'
    | '/docs/$'
    | '/dashboard'
    | '/docs'
    | '/dashboard/video/$workspaceId'
    | '/dashboard/video'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/ai-images'
    | '/dashboard/images'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/status'
    | '/dashboard/video'
    | '/docs/$'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/video/$workspaceId'
    | '/dashboard/video/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/video': {
      id: '/dashboard/video'
      path: '/video'
      fullPath: '/dashboard/video'
      preLoaderRoute: typeof DashboardVideoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/status': {
      id: '/dashboard/status'
      path: '/status'
      fullPath: '/dashboard/status'
      preLoaderRoute: typeof DashboardStatusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/images': {
      id: '/dashboard/images'
      path: '/images'
      fullPath: '/dashboard/images'
      preLoaderRoute: typeof DashboardImagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-images': {
      id: '/dashboard/ai-images'
      path: '/ai-images'
      fullPath: '/dashboard/ai-images'
      preLoaderRoute: typeof DashboardAiImagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/video/': {
      id: '/dashboard/video/'
      path: '/'
      fullPath: '/dashboard/video/'
      preLoaderRoute: typeof DashboardVideoIndexRouteImport
      parentRoute: typeof DashboardVideoRoute
    }
    '/dashboard/video/$workspaceId': {
      id: '/dashboard/video/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/dashboard/video/$workspaceId'
      preLoaderRoute: typeof DashboardVideoWorkspaceIdRouteImport
      parentRoute: typeof DashboardVideoRoute
    }
  }
}

interface DashboardVideoRouteChildren {
  DashboardVideoWorkspaceIdRoute: typeof DashboardVideoWorkspaceIdRoute
  DashboardVideoIndexRoute: typeof DashboardVideoIndexRoute
}

const DashboardVideoRouteChildren: DashboardVideoRouteChildren = {
  DashboardVideoWorkspaceIdRoute: DashboardVideoWorkspaceIdRoute,
  DashboardVideoIndexRoute: DashboardVideoIndexRoute,
}

const DashboardVideoRouteWithChildren = DashboardVideoRoute._addFileChildren(
  DashboardVideoRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAiImagesRoute: typeof DashboardAiImagesRoute
  DashboardImagesRoute: typeof DashboardImagesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStatusRoute: typeof DashboardStatusRoute
  DashboardVideoRoute: typeof DashboardVideoRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiImagesRoute: DashboardAiImagesRoute,
  DashboardImagesRoute: DashboardImagesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStatusRoute: DashboardStatusRoute,
  DashboardVideoRoute: DashboardVideoRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
