/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTrashRouteImport } from './routes/dashboard/trash'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardCanvasRouteImport } from './routes/dashboard/canvas'
import { Route as DashboardAiImagesRouteImport } from './routes/dashboard/ai-images'
import { Route as DashboardActivityRouteImport } from './routes/dashboard/activity'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardEditImageIdRouteImport } from './routes/dashboard/edit.$imageId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrashRoute = DashboardTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCanvasRoute = DashboardCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiImagesRoute = DashboardAiImagesRouteImport.update({
  id: '/ai-images',
  path: '/ai-images',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditImageIdRoute = DashboardEditImageIdRouteImport.update({
  id: '/edit/$imageId',
  path: '/edit/$imageId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/ai-images': typeof DashboardAiImagesRoute
  '/dashboard/canvas': typeof DashboardCanvasRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit/$imageId': typeof DashboardEditImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/ai-images': typeof DashboardAiImagesRoute
  '/dashboard/canvas': typeof DashboardCanvasRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/edit/$imageId': typeof DashboardEditImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/ai-images': typeof DashboardAiImagesRoute
  '/dashboard/canvas': typeof DashboardCanvasRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trash': typeof DashboardTrashRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/edit/$imageId': typeof DashboardEditImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard/account'
    | '/dashboard/activity'
    | '/dashboard/ai-images'
    | '/dashboard/canvas'
    | '/dashboard/settings'
    | '/dashboard/trash'
    | '/dashboard/'
    | '/dashboard/edit/$imageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard/account'
    | '/dashboard/activity'
    | '/dashboard/ai-images'
    | '/dashboard/canvas'
    | '/dashboard/settings'
    | '/dashboard/trash'
    | '/dashboard'
    | '/dashboard/edit/$imageId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard/account'
    | '/dashboard/activity'
    | '/dashboard/ai-images'
    | '/dashboard/canvas'
    | '/dashboard/settings'
    | '/dashboard/trash'
    | '/dashboard/'
    | '/dashboard/edit/$imageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trash': {
      id: '/dashboard/trash'
      path: '/trash'
      fullPath: '/dashboard/trash'
      preLoaderRoute: typeof DashboardTrashRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/canvas': {
      id: '/dashboard/canvas'
      path: '/canvas'
      fullPath: '/dashboard/canvas'
      preLoaderRoute: typeof DashboardCanvasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-images': {
      id: '/dashboard/ai-images'
      path: '/ai-images'
      fullPath: '/dashboard/ai-images'
      preLoaderRoute: typeof DashboardAiImagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edit/$imageId': {
      id: '/dashboard/edit/$imageId'
      path: '/edit/$imageId'
      fullPath: '/dashboard/edit/$imageId'
      preLoaderRoute: typeof DashboardEditImageIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardAiImagesRoute: typeof DashboardAiImagesRoute
  DashboardCanvasRoute: typeof DashboardCanvasRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTrashRoute: typeof DashboardTrashRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEditImageIdRoute: typeof DashboardEditImageIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardAiImagesRoute: DashboardAiImagesRoute,
  DashboardCanvasRoute: DashboardCanvasRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTrashRoute: DashboardTrashRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEditImageIdRoute: DashboardEditImageIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
